version: '2.1'

services:

  main-db:
    container_name: main-db
    build: ./services/main/project/db
    ports:
        - 5435:5432  # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  main-service:
    container_name: main-service
    build: ./services/main/
    volumes:
      - './services/main:/usr/src/app'
    ports:
      - 5001:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@main-db:5432/main_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@main-db:5432/main_test
    depends_on:
      main-db:
        condition: service_healthy
    links:
      - main-db

  nginx:
    container_name: nginx
    build: ./nginx/
    restart: always
    ports:
      - 80:80
    depends_on:
      main-service:
        condition: service_started
    links:
      - main-service
